### ISSUE TITLE
这个项目怎么好像跑不动  是什么原因啊

### ISSUE THREAD

**Issue by 5945xiangxiang** [yangyifanNeu/DLMUsecondhandmarket#1]

**Comment by yangyifanNeu** [comment]
后端代码和sql脚本在server文件夹里，数据库用mysql，内存数据库redis

**Comment by yangyifanNeu** [comment]
> _No description provided._

后端代码和sql脚本在server文件夹里，数据库用mysql，内存数据库redis

**Comment by yangyifanNeu** [comment]
@5945xiangxiang

**Comment by 5945xiangxiang** [comment]
有联系方式不 ，可以详细请教一下不

**Comment by yangyifanNeu** [comment]
> 有联系方式不 ，可以详细请教一下不

[yangyifanneu@163.com](mailto:yangyifanneu@163.com)  可以发我邮箱哈
